cstate/cstate

- layouts/index.html
> fixed systems loop

- README.md
- While reading through the readme, I noticed that this sentence seemed to be missing a word.
> (doc) Minor correction

- layouts/partials/footer.html
Replaced `2.0.1` with `2.0.2`.
closes #39
> Fixed the version string in the footer for v2.0.2

- i18n/fr.yaml
- static/admin/config.yml
I added the French language.
Can you modify the "Add your translations" documentation?
It seems to me that we need to change `static/admin/config.yml` and not `static/admin/index.html`.
Thank you, have a good day.
> Addition of French language

- i18n/de.yaml
- static/admin/config.yml
**Test plan**
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
> Added german translation

- i18n/tr.yaml
- static/admin/config.yml
There seems to be a German translation PR and if either is merged, it will cause a conflict and I guess the repo owner should cherry pick or so to resolve conflicts.
> Added turkish translation

- i18n/de.yaml
> additional translations for german lang

- i18n/pt.yaml
- static/admin/config.yml
This PR adds Portuguese as a language on the platform.
---
Closes #68
> Add Portuguese

- static/admin/index.html
* Add Portuguese - #69 @dmcclccam
* Fixed Netlify CMS preview - #63
> cState v3.1.1

- README.md
I don't know if this absence is because is too obvious, but I couldn't leave it behind. I hope you can fix it proper English phrasing, as English is not my mother language.
**Test plan**
Put `closes #XXXX` in your comment to auto-close the issue that your PR …
> Update README.md with an extra step

- layouts/partials/meta.html
> Add prefers-color-scheme dark theme

- i18n/de.yaml
Fix typo in german i18n-file
closes #88
> #88 / #89 - fix DE i18n typo

- README.md
I added the status page of Uberspace into the readme.
> Add Uberspace Example Status Page

- README.md
Uberspace switched to cachet
**Test plan**
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
> add fsci to cstate users, remove uberspace

- layouts/issues/issue.html
- layouts/partials/index/announcements.html
- layouts/partials/index/components.html
Cf. # 115 for details.
closes #115
> Append a trailing slash to all 'affected' URLs

- i18n/nl.yaml
> added dutch translation

- i18n/pt.yaml
- static/admin/config.yml
I make a translation for portuguese language =)
> translation add for portuguese language

- i18n/mk.yaml
- static/admin/config.yml
Adding Macedonian Translations.
**Test plan**
Closes #140
> Adding macedonian translations.

- README.md
Adding a new example, https://status.sthse.co, to the README under examples section.
> Add Storehouse to Examples Section

- README.md
- exampleSite/config.yml
- exampleSite/content/issues/2019-10-08-testing-new-pipeline.md
- exampleSite/content/issues/2020-06-13-maintenance-window.md
- i18n/de.yaml
- i18n/en.yaml
- i18n/fr.yaml
- i18n/lt.yaml
- i18n/mk.yaml
- i18n/nl.yaml
- i18n/pt.yaml
- layouts/issues/issue.html
- layouts/partials/header.html
- layouts/partials/index/announcements.html
- layouts/partials/index/components.html
- layouts/partials/index/incidents-yearly.html
- layouts/partials/index/tabs.html
- layouts/partials/meta.html
- static/admin/config.yml
This update fixes some somewhat significant bugs like with official support for **non-root directories**, adds a lot of **translations**, and improves upon other **quality of life** aspects of cState. including **Netlify CMS updates*.
There are changes to default CSS, see changelog.
More exciting things coming soon.
* **Massive translations update** Thank you, #hacktoberfest members!
* **Added Dutch translation** #133 
* **Updated German translation** #132 
* **Updated French translations** #134
* **Added Portugese translation** #137 
* **Added Macedonian translation** #141 
* **Bugfix** #126 - support for non-root directories
* **Low to medium priority - new feature** You can now [filter issues on Netlify CMS (click to see screenshot …
> cState v4.4 Hacktoberfest Edition

- README.md
> Added "Hyrousek" status page

- i18n/it.yaml
- static/admin/config.yml
This pull request adds the Italian translation :-)
> Add Italian translation

- README.md
- exampleSite/content/issues/2021-02-13-maintenance-window.md
- i18n/en.yaml
- layouts/index.json
- layouts/partials/js.html
- layouts/partials/meta.html
> Bugfix for #180

- i18n/de.yaml
Just small typos in German translation
> fix typos in German translation

- i18n/de.yaml
Just fixed a typo and punctuation.
> Fixed typo and punctuation

- README.md
- layouts/issues/small.html
This closes #196 by adding the "UTC" to the partial `small.html` as it is in the other branch of the if statement. 
**Test plan**
I've done the tiny change on our internal status page theme and ran `hugo serve`. Times ended up as expected. 
closes #196
> Fix relative date for resolved issues and non-UTC browser timezone.

- exampleSite/netlify.toml
**Test plan**
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
> Attempt to fix #230

- README.md
Fixes a typo in README.md
Like has been typoed as liek.
> Fix liek to like

- i18n/ja.yaml
- static/admin/config.yml
> Add Japanese Translate

- exampleSite/content/issues/2023-04-16-formatting-testing.md
- layouts/partials/meta.html
Solve [code blocks overflowing the containers](https://github.com/cstate/cstate/issues/263) (which pretty much already has the solution). Also includes an example page with the code block.
(Merging into master because dev doesn't exist. Request for rebase if necessary to switch the branch being merged into.)
**Test plan**
Demonstrate the code is solid. Example: The exact commands you ran and their output, …
> Contain the code blocks & add example page for formatted markdown

- i18n/uk.yaml
- static/admin/config.yml
https://github.com/cstate/cstate/issues/290
> Ukrainian Language

- layouts/issues/issue.html
- layouts/issues/single.html
- layouts/issues/small.html
- layouts/partials/js.html
> use dateFormat instead of .Date.Format for better localization

- i18n/uk.yaml
- layouts/issues/single.json
Updated default Ukrainian language file
> Updated default Ukrainian language file 

- i18n/id.yaml
- static/admin/config.yml
> Add Indonesian translation

- i18n/pl.yaml
> Add Polish translation

- README.md
Add Testing Farm status dashboard example
> Add Testing Farm status dashboard example

- i18n/ru.yaml
- static/admin/config.yml
* Create ru.yaml
* Add ru to config.yml
> Added Russian language support

- es.yaml
- static/admin/config.yml
Adding spanish translations
**Test plan**
- Change config to `es` and check that the translations are applied
closes #322
> feat: adds spanish translations

- layouts/partials/js.html
- layouts/partials/meta.html
thank you to the contributor for the PR!
> add spanish to master

- i18n/ro.yaml
- static/admin/config.yml
Added **romanian** translations
**Test plan**
- Change config to `ro` and check that the translations are applied
closes #334
> Added Romanian language
