cstate/cstate

layouts/partials/meta.html

Fixes #32 
I'm running this on my own status pages, so it is well tested. It is the recommended way to do this according to Hugo as well: https://gohugo.io/templates/rss/

Add links to RSS feeds

---

static/admin/config.yml

According to the documentation [here](https://www.netlifycms.org/docs/widgets/) for Boolean (you may need to select the type) a Boolean can have a default applied to it. The default when creating a new issue and nothing being changed in the `Resolved` switch should be to default to `false`.
As issue #65 says, if you do not have a `resolved` field in the incident metadata the components / systems will not be given the severity you have specified in the incident.
Closes #65

Fix issue of missing resolved field in Netlify

---

layouts/partials/index/components.html

The change in pull request #99 has inverted arguments, therefore the overridden `displayName` is never taken into account. This change puts them in the correct order according to the [documentation](https://gohugo.io/functions/default/) and actually closes #98 .

use name as default when overriding system display name

---

exampleSite/config.yml
layouts/index.html
layouts/index.xml
layouts/partials/footer.html
layouts/partials/index/tabs.html
static/admin/config.yml

The new option enableIncidentHistory allows to enable or disable the incident history. This includes:
- No RSS feed
- No incident history in the home page
- (If easily achievable) No rendering of single incident pages, which are resolved. Note: This is not implemented in this PR, because I am not sure, if this is possible with hugo.
I would like to disable the incident history, as I do not need and and only want to show the current status of my systems.
**Test plan**
Just set enableIncidentHistory to false in the exampleSite and the incident history should be gone.

Add config option to disable incident history

---

layouts/partials/meta.html

closes #113
Just a small mistake in the partial I believe, cf code.

Fix parameter name for headerTextColor

---

Dockerfile
docker/entrypoint.sh

This patch adds a Dockerfile to cstate, it's technically related to #50 - which was closed because I was too lazy to get this done. But here it is.
Adding a Dockerfile allows cstate to operate without a serverless system, such as Netlify, but also makes development a little easier as you don't need to install the required dependencies onto your machine, such as Hugo. This can make development on non-UNIX based systems a little easier and removes the requirement of installing Hugo to develop cstate.
This PR adds two new files: Dockerfile & docker/entrypoint.sh
The Dockerfile configures the Docker image, pulls cstate and configures it for first run.
The entrypoint script file exists to build cstate on every startup. This is required as all files are compiled into the public directory.
Once …

Add Dockerfile to cstate

---

static/admin/config.yml

Changed the `untited` to `untitled` which caused errors when using the Netlify CMS as described in #144
All information is in #144 I have rectified that and it works. 
closes #144

Changed the untited to untitled

---

exampleSite/config.yml
layouts/issues/small.html
layouts/partials/index/summary.html
layouts/partials/js.html

This PR adds support for relative timestamps using the existing `timeSince()` function to incident history and issue summaries, and shared with the Last checked logic too.
Enabling this is controlled by setting `.Site.Params.useRelativeTime` to true. I defaulted it on, we can easily turn it off if you think that's a better default.
I believe this Closes #128 primarily, but I also added `.Site.Params.skipSeconds` which I believe Closes #135.

135 relative times

---

Dockerfile
README.md
docker/entrypoint.sh

This PR should resolve #160 - the issue seems to be with the entrypoint being encoded with CRLF line endings, I've also added some extra debugging messages to the entrypoint script, to make diagnosing future Docker-related issues easier.
I'd also like to suggest building the cState Dockerfile into an image and publishing it on Docker Hub or GitHub Packages for ease of deployment. This would also make a docker-compose.yaml file possible (or at least, more user friendly). GitHub Actions are able to build the images, it doesn't take long as we're only compiling the site with Hugo at run-time.
I've also updated the Dockerfile to only clone the master branch of cstate/example, and only get the latest commit - this will hopefully improve the build speed of the image.
I'd also like to suggest …

Docker: entrypoint script fixes

---

exampleSite/config.yml

I was confused when reading the sample config file, as explained in #164. "don't support /" could have meant a trailing slash, or subdirectories, or at least wasn't exactly clear to me. By adding an explicit example of a broken behavior, we make it clear what we're talking about here, and what to avoid.
Closes #164

clarify what doesn't work as a baseURL

---

README.md
exampleSite/vercel.json

I created a vercel.json file, which is their equivalent of a netlify.toml file. This will allow cross origin requests.

Allow cross origin on Vercel deployments

---

README.md

Their status page is no longer present, as they seem to be changing their business model entirely.

Remove Storehouse from the README examples

---

README.md
i18n/de.yaml
layouts/index.json
layouts/issues/small.html
layouts/partials/js.html
layouts/partials/meta.html

* Raw unformatted Markdown for a site description will no longer show up in SEO tags
* German translation i18n fix
* Bugfix for pages that use relative time (now it's calculated based on the correct time zone) #197

Bug fixes v5.0.4

---

layouts/index.json
layouts/partials/js.html
layouts/partials/meta.html

v5.0.5 includes:
- #199 the date for future issues is shown instead of "ongoing" which is confusing if it hasn't even started
This has prompted a discussion about maintenance issues and how to make them work better which will be addressed in a future release.
- #204 this release also fixes an invalid JSON template
- typo fixes by community members
The updates in this release were pushed to the master branch earlier but didn't receive an official release (meaning you could have a v5.0.4 release which was compiled from different source code depending on where you found it). This update is official and will show up as v5.0.5 when checked in console and all the other usual places.
This repo is starred by 1425 people as of midnight October 1st. Make sure to read #207 and join Hacktoberfest …

cState v5.0.5

---

exampleSite/config.yml
layouts/_default/list.svg
layouts/affected/list.json
layouts/index.json
layouts/partials/js.html
layouts/partials/meta.html

Changelog:
Today we're celebrating Hacktoberfest with a critical bugfix to the JSON API so it works properly when checking _for a singular component status_ (unneeded `,` removed) and expanding 'shields' - SVG badges - to show status for ANY component as per a user suggestion - #208.
**You will need to change the config.yml file for this feature to be enabled. (If you use Netlify CMS, just update your site configuration and the SVG links for specific components will start working after the next deploy.)**
This is what your `outputs` should look like:
```
outputs:
page:
- html
- json
section:
- html
- json
- rss
home:
- html
- json
- rss
- svg
term:
- html
- json
- rss
- svg
```
Notice that `svg` is now added to the bottom under `term` as well as `home`.
Once you've done that, go to …

cState v5.1

---

layouts/_default/list.xml
layouts/index.xml

According to the RSS spec a feed needs to specify the xml version:
* https://validator.w3.org/feed/docs/error/BadXmlVersion.html
**Test plan**
index.xml should contain `<?xml version="1.0" encoding="utf-8"?>` as first content
none

[TASK] add xml declaration to provide clean xml code for all readers

---

exampleSite/config.yml
layouts/partials/index/components.html
layouts/partials/meta.html

Discussion previously occurred in #214 
This PR adds a new optional field to components in config.yml for an external url. The intent of this change is to allow cstate administrators to directly link to services/components that have web frontends.
Based on [conversation](https://github.com/cstate/cstate/issues/214#issuecomment-981752806) with @mistermantas, the `🔗` unicode character was chosen to represent the link as the only candidate that consistently rendered across all browsers.
Alternatives previously considered:
```
🡭 U+1F86D
🡵 U+1F875
🢅 U+1F885
```
**Test plan**
The change can be enabled or disabled by specifying or omitting the newly added field `link`. I have enabled it by default for a new component in exampleSite/config.yml to demonstrate its existence to new users.
```yaml …
```

External link button to link to a component

---

exampleSite/config.yml
exampleSite/netlify.toml
layouts/_default/list.xml
layouts/index.json
layouts/index.xml
layouts/issues/small.html
layouts/partials/index/components.html
layouts/partials/js.html
layouts/partials/meta.html

Mostly bugfixes but there's a nice added feature for the components:
- Fixed RSS XML formatting - #228, #216
- Additionally, RSS by default now has the correct CORS headers. You can change them manually in a headers file if you're upgrading (for example, netlify.toml) - #221
- Fixed some style inconsistencies - #223 213
- Introduced `link` as an optional attribute for a component/system. Link to a frontend right from cState's systems list! Thanks @aperullo for an excellent solution - see #223

cState v5.3

---

layouts/_default/list.html
layouts/partials/index/incidents.html

The currently used "triangle-headed" arrows are from the Unicode code
block "Supplemental Arrows-C" [1], which seems to be not widely
supported. This also applies to e.g. Roboto, which is being explicitly
used in the CSS.
Instead, use the "simple" arrows from the "Arrows" block, which is much
more widely supported by fonts.
[1]: https://en.wikipedia.org/wiki/Supplemental_Arrows-C
closes #242

layout: use simple arrows as list pagination icons

---

layouts/issues/single.html
layouts/partials/index/components.html

This PR stops forcefully converting the last modified date into UTC to respect Hugo's `timeZone` configuration.
As described in https://github.com/cstate/cstate/pull/249#issue-1426673086, I understand this will be a breaking change.  If we should keep backward compatibility, I will open another PR to introduce `params.forceUTCInLastMod` (key name is subject to discuss).
**Test plan**
No particular test plan because the change is small. I checked in my local as below:
- `config.yaml`:
```yaml
timeZone: Asia/Tokyo
params:
dateFormat: January 2, 2006 at 3:04 PM MST
shortDateFormat: 15:04 MST — Jan 2
enableLastMod: true
```
- last modified info in git:
```console
❯ git …
```

Respect timezone even in last modified date when `timeZone` was set

---

README.md
exampleSite/netlify.toml
exampleSite/static/_headers
layouts/index.json
layouts/partials/index/announcements.html
layouts/partials/index/components.html
layouts/partials/js.html
layouts/partials/meta.html

cstate turns 5 years old this year! happy hacktoberfest!
- #243 – replace icons to be better supported across operating systems
- #246 - translation bugfix  (disrupted label did not show)
- #248 - Respect timezone even in last modified date when timeZone was set
- Better out of the box support for Cloudflare Pages:
To allow for the reading of API output by default on CF Pages, a `_headers` file is now added to /static/ from this version on. Netlify still has `netlify.toml` from the root. https://developers.cloudflare.com/pages/platform/headers/
this update is mostly supposed to coincide with html-embed

cState v5.5 Dev

---

layouts/issues/issue.html
layouts/partials/index/announcements.html
layouts/partials/index/components.html

When run with `cd exampleSite && hugo serve --baseUrl=http://localhost/cstate/ --theme=cstate --themesDir=../.. --verbose` on Hugo v0.101.0 and above, the services on the main page at `[localhost]/cstate/` and individual issues should now correctly link to `[localhost]/cstate/affected/[service]` instead of `[localhost]/affected/[service]`.
No visible changes on older versions or without a subdirectory.
Fixes #251

Fix affected links in subdir to work with Hugo v0.101+

---

Dockerfile
exampleSite/config.yml

1. Dockerfile now uses `exampleSite/` in this repo as the example site, instead of a remote git repo. (So fixing #260 does not depends on fixing a remote git repo).
2. Disable enableGitInfo in example site so hugo doesn't complain.

Fix hugo fails to run for docker build

---

README.md

Hello,
going through the provided example websites I realized that some of them are no longer available. I've removed them from the README.md file.

Remove deprecated example pages

---

README.md
layouts/issues/issue.html
layouts/issues/small.html

**Summary**
Issues history (including individual issues view) currently always shows `Resolved after <x time> of Downtime` even if the issue severity is marked as `disrupted`.
This change seeks to remove the `of Downtime` or language equivalent if the issue severity is anything other than `down`. The approach is to avoid grammar and i18n changes while also acknowledging the issue's severity.
**Change**
Minimal change to only apply the `ofDowntime` mapped text if the issue severity is `down`
**Test plan**
*Pre-Reqs*
* Have an issues matching to following criteria
* severity is `down` and resolved after time diff is over 1 minute
* severity is `disrupted` and resolved after time diff is over 1 minute
* severity is `down` and resolved after time diff is over 1 hour
* severity is `disrupted` …

Severity aware resolution

---

layouts/index.json

> Please provide enough information so that others can review your pull request:
This PR adds a `pinnedIssues` key to the `index.json` object, which contains issues with `informational` and `pin` set to `true`. The issue objects are very similar to the ones in `unresolvedIssues` for systems, but I've omitted some values that I deemed unnecessary for this specific use (e.g. `.informational` would have always been `true`) -- please let me know if this is fine or if I should re-add some of them.
> Explain the **details** for making this change. What existing problem does the pull request solve?
I would like to access the pinned issues for a particular status page from other services programatically, but there's no way to do that except for scraping the generated HTML pages. This pull request …

Expose pinned issue(s) in index.json

---

layouts/partials/meta.html

**Test plan**
With this fix:
Untested on IE8+, but it should work based on the [compatibility table for overflow-wrap](https://caniuse.com/mdn-css_properties_overflow-wrap_break-word).
Closes #285

Use overflow-wrap on headings
